---
- name: Simple tasks
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Add the user 'myuser2'
      ansible.builtin.user:
        name: myuser2

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        force_apt_get: true
        upgrade: dist

    - name: Install ZSH, Git...
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - zsh
          - git
          - acl
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: myuser
        - username: ubuntu
        - username: myuser2
      oh_my_zsh_plugins:
        - git
        - microk8s
        - kubectl
