---
- name: Ansible Playbooks on Semaphore
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Add the user 'myuser'
      ansible.builtin.user:
        name: myuser
    - name: Upgrade all apt packages
      ansible.builtin.apt:
        force_apt_get: true
        upgrade: dist
